### ISSUE TITLE
FEATURE REQUEST: Display multiple tables in a single widget, separated by tabs

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-ipywidgets#11]
As a user, I'd like the ability to display more than one table in a DeephavenWidget. These would be separated by tabs, just like you can do with panels in the IDE. This could apply to plots as well, or other Deephaven widgets.

**Comment by dsmmcken** [comment]
Good suggestion. This should be something that user will be able to accomplish with our programmatic layout feature when that becomes available.

Closing as WNI.
