### ISSUE TITLE
A flag to force a widget to follow the bottom of a ticking table

### ISSUE THREAD

**Issue by jjbrosnan** [deephaven/deephaven-ipywidgets#48]
As it stands, if you display a widget of a ticking table, you have to use your scroll wheel to force the widget to follow the ticking data unless it's reversed so new rows show up at the top.

It would be nice if you could pass a flag as argument to force the widget instead to follow the bottom of the table as it ticks:

```python
display(DeephavenWidget(t, follow_last=True))
```

**Comment by jnumainville** [comment]
This seems more appropriate to add to `ui.table`. Created https://github.com/deephaven/deephaven-plugins/issues/700
